name: "[ACTION] Auto Release"
description: "A composite action to handle auto releases"
author: "Godners Ren"

branding:
  icon: 'package'
  color: 'red'

inputs:
  GITHUB_TOKEN:
    description: "The GitHub Token from the calling repository"
    required: true
    
outputs:
  has_changes:
    description: "Whether there are new changes to release"
    value: ${{ steps.worker-check.outputs.has_changes }}
  release_tag:
    description: "The tag generated for the release"
    value: ${{ steps.worker-info.outputs.release_tag }}
    
runs:
  using: "composite"
  steps:
    - name: "[STEP] Validate Token Inputed via Bash Script"
      id: validate
      shell: bash
      run: bash ${{ github.action_path }}/validate.bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: "[STEP] Check if Checkout via Bash Script"
      id: checked-out
      shell: bash
      run: bash ${{ github.action_path }}/checked-out.bash
        
    - name: "[STEP] Run Checkout Repository via GitHub Action"
      if: steps.checked-out.outputs.checked_out == 'false'
      id: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0
        token: ${{ inputs.GITHUB_TOKEN }}

    - name: "[STEP] Worker (Check) via Bash Script"
      id: worker-check
      shell: bash
      run: bash ${{ github.action_path }}/worker-check.bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    
    - name: "[STEP] Print Summary (NO Changes) via Bash Script"
      id: summary-no-changes
      if: steps.worker-check.outputs.has_changes == 'false'
      shell: bash
      run: bash ${{ github.action_path }}/summary-no-changes.bash
    
    - name: "[STEP] Worker (Info) via Bash Script"
      id: worker-info
      if: steps.worker-check.outputs.has_changes == 'true'
      shell: bash
      run: bash ${{ github.action_path }}/worker-info.bash

    - name: "[STEP] Remove Existent Release via Bash Script"
      id: remove
      if: steps.worker-check.outputs.has_changes == 'true'
      shell: bash
      run: bash ${{ github.action_path }}/remove.bash
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        RELEASE_TAG: ${{ steps.worker-info.outputs.release_tag }}
      
    - name: "[STEP] Create New Release via SoftProps Action"
      id: Create
      if: steps.worker-check.outputs.has_changes == 'true'
      uses: softprops/action-gh-release@master
      with:
        tag_name: ${{ steps.worker-info.outputs.release_tag }}
        name: ${{ steps.worker-info.outputs.release_tag }}
        body: |
          - TAG: ${{ steps.worker-info.outputs.release_tag }}
          - TIME: ${{ steps.worker-info.outputs.time }}
          - NOTE: This Release Created by Workflow [Auto-Release]
          - URL: <https://github.com/marketplace/actions/action-auto-release>
        draft: false
        prerelease: false

    - name: "[STEP] Print Summary (Has Changes) via Bash Script"
      id: summary-has-changes
      if: steps.worker-check.outputs.has_changes == 'true'
      shell: bash
      run: bash ${{ github.action_path }}/summary-has-changes.bash
